# Generated by Django 3.1 on 2020-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyOnlineStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=50)),
                ('student_phone_no', models.CharField(max_length=50)),
                ('student_address', models.CharField(max_length=50)),
            ],
        ),
    ]
